#!/usr/bin/env bash
# .husky/pre-commit
#
# SPDX-License-Identifier: CC-BY-4.0 OR GPL-3.0-or-later
# This file is part of Network Pro.

# Run Mocha and Chai test suite
npm test

# Lint all JavaScript files
# Exclude .dist/js/ due to unknown issue
npx eslint --cache --cache-location .eslintcache --ext .js,.cjs,.mjs --ignore-pattern node_modules/ --ignore-pattern dist/js/ --ignore-pattern coverage/ .

# Run markdownlint-cli2 on all Markdown files
npx markdownlint-cli2 "**/*.{md,markdown}" "#node_modules/**" "#coverage/**"

# Run stylelint against all CSS files
npx stylelint "**/*.css" "!node_modules/**" "!dist/**" "!coverage/**"

# Run prettier against all staged files
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

git update-index --again

exit 0
